### PR TITLE
update project to support flutter `v3.22.0`

### LINKED ISSUE #17: The getter 'bodyText1' isn't defined for the class 'TextTheme'
Hi,

Context Menu is failing to upgrade to latest version.

### PR DESCRIPTION
**Pull request by Juliotati**
- fixes #17

### CODE REVIEW

**Comment by rodrigo-itao** [comment]
Hi @esDotDev , could you please review and merge this PR? Thank you in advance

**Comment by esDotDev** [comment]
Done, thanks for the updates!

**Comment by anidotnet** [comment]
Any date for the 1.1.0 release?

**Comment by xuancat0208** [comment]
1.1.0 release please.

**Comment by Juliotati** [comment]
@xuancat0208 @anidotnet in the mean time you can use the updated version straight from my fork:

Always on the latest
```yml
  context_menus:
    git:
      url: https://github.com/juliotati/flutter-context-menu.git
      ref: master
```

Or ensure usage of the exact commit where the migration was done
```yml
  context_menus:
    git:
      url: https://github.com/juliotati/flutter-context-menu.git
      ref: 79dbf0ee78a4e5c2b0e7f2f371bb415d238f594c
```

**Comment by esDotDev** [comment]
Hey guys, sorry for the delay here, just been a little swamped at work. Will get this pushed shortly, just a few other maintenance issues I want to get too for the next release.

**Comment by esDotDev** [comment]
v 1.1.1 was pushed, also pushed v.2.0.0 that adds support for Tap and various combinations of Tap, SecondaryTap and LongPress.

**Pull request merged**
